import { Component, Inject } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { AddCategoryComponent } from '../../category/add-category/add-category.component';
import { UtilsService } from '../../serviceutils/utils.service';
import { ActivityService } from '../../services/activity.service';
import { Activity } from '../activity';
import { NgFor, NgIf } from '@angular/common';
import { CategoryService } from '../../services/category.service';
import { Category } from '../../category/category';
import {FileHandleModule} from "../../file-handle/file-handle.module";
import {DomSanitizer} from "@angular/platform-browser";

@Component({
  selector: 'app-add-activity',
  standalone: true,
  imports: [ReactiveFormsModule,NgIf,NgFor],
  templateUrl: './add-activity.component.html',
  styleUrl: './add-activity.component.css'
})

export class AddActivityComponent
{
  activityFormValue !: FormGroup
  isAddOperation = true
  activityId: number
  categories : any
  categoryObject!: Category
  isValidForm = true
  cate: any

  activity = new Activity(
    "",
    "",
    "",
    new Category("", "", "", []),
    []
  )


  constructor(
    private activityFormBuilder: FormBuilder,
    private activityService: ActivityService,
    private categoryService: CategoryService,
    private utilsService: UtilsService,
    private dialogRef: MatDialogRef<AddCategoryComponent>,
    @Inject(MAT_DIALOG_DATA) public data: any,
    private sanitizer: DomSanitizer) { this.activityId = data.activityId }

  ngOnInit()
  {
    if (this.activityId)
    {
      this.isAddOperation = false;
      this.getActivityById(this.activityId)
    }

    this.activityFormValue = this.activityFormBuilder.group({
      activityName : ['',Validators.required],
      activityDescription : ['',Validators.required],
      activityImage : ['',Validators.required],
      activityCategory:['',Validators.required]
    })

    this.getAllCategories()
  }

  updateActivity(id:any)
  {
      this.activity.actId = id
      this.activity.actName = this.activityFormValue.value.activityName
      this.activity.actDescription = this.activityFormValue.value.activityDescription
      this.activity.category = this.categoryObject


    if (this.activity.actImages.length > 0)
    {
        const formData = this.prepareFormData(this.activity)

        this.activityService.updateActivity(formData).subscribe({
          complete: () => {
            this.dialogRef.close()
            this.utilsService.openDialog("Opération réussite", "Activité éditée avec succès", true)
          },
          error: (err) => this.utilsService.openDialog("Opération échouée", err.message, false)
        })
    }
    else
    {
        this.activityService.updateActivityData(id, this.activity).subscribe({
          complete: () => {
            this.dialogRef.close()
            this.utilsService.openDialog("Opération réussite", "Activité éditée avec succès", true)
          },
          error: (err) => this.utilsService.openDialog("Opération échouée", err.message, false)
        })
    }
  }

  closeDialog()
  {
    this.dialogRef.close()
  }

  getActivityById(id: number) 
  {
    this.activityService.getActivity(id).subscribe({
      next: (activity) => this.populateUpdateForm(activity),
      error: (err) => console.error(err)
    })
  }

  populateUpdateForm(activity: any)
  {
    this.categoryObject = activity.category

    let optionTag!: HTMLOptionElement
    let selectTag!: HTMLSelectElement

    this.activityFormValue.controls['activityName'].setValue(activity.actName)
    this.activityFormValue.controls['activityDescription'].setValue(activity.actDescription)

    // get the div tag containing select list of categories
    let formGroupCategorySelectList = document.getElementById("categorySelectList")?.parentElement

    // get the reference of div tag containing select list of categories generated by Angular (example: _ngcontent-ng-c1135787114)
    let reference = document.getElementById("categorySelectList")?.parentElement?.attributes.item(0)?.name

    //remove actual select HTML tag
    document.getElementById("categorySelectList")?.remove()

    // create new select HTML tag for replace the removed one
    selectTag = document.createElement("select") // <select ${reference}="" formcontrolname="activityCategory" class="form-control border border-dark pl-2 round ng-pristine ng-valid ng-touched"></select>
    selectTag.setAttribute(reference!,"")
    selectTag.setAttribute("formcontrolname","activityCategory")
    selectTag.setAttribute("class","form-control border border-dark pl-2 round ng-pristine ng-valid ng-touched")
    selectTag.setAttribute("id","categorySelectList")
    selectTag.addEventListener('change',()=>{
      this.getCategory(selectTag[selectTag.selectedIndex].getAttribute("value"))
    })
    formGroupCategorySelectList?.appendChild(selectTag)

    //add option HTML tag to select tag that will be selected by default
    let categorySelectList = document.getElementById("categorySelectList")
    optionTag = document.createElement("option") //<option _ngcontent-ng-c1135787114="" value="4" ng-reflect-value="4">ala</option>
    optionTag.setAttribute(reference!,"")
    optionTag.setAttribute("value",activity.category.catId.toString())
    optionTag.setAttribute("ng-reflect-value",activity.category.catId.toString())
    optionTag.textContent = activity.category.catName
    categorySelectList?.appendChild(optionTag)

    this.categoryService.getAllCategories().subscribe({
      next:(category)=>{

      for (let i = 0; i < category.length; i++)
      {
        if (category[i].catId != activity.category.catId)
        {
          // add the other options for categories
          optionTag = document.createElement("option")
          optionTag.setAttribute(reference!,"")
          optionTag.setAttribute("value",category[i].catId.toString())
          optionTag.setAttribute("ng-reflect-value",category[i].catId.toString())
          optionTag.textContent = category[i].catName
          categorySelectList?.appendChild(optionTag)
        }
      }
    },
      error: (err)=>console.error(err)
    })

  }

  getAllCategories()
  {
    this.categoryService.getAllCategories().subscribe({
      next: (category) => this.categories = category as Category,
      error: (err) => console.error(err)
    })
  }

  getCategory(id?: any)
  {
    if (!id)
    {
      this.categoryService.getCategory(this.activityFormValue.value.activityCategory).subscribe({
        next: (cat) =>{
          this.categoryObject = cat as Category
          console.log(this.categoryObject)
        },
        error: (err) => console.log(err)
      })
    }
    else
    {
      this.categoryService.getCategory(id).subscribe({
        next: (cat) => {
          this.categoryObject = cat as Category
          console.log(this.categoryObject)
        },
        error: (err) => console.log(err)
      })
    }

  }


  checkValidityForm()
  {
    // check activity name and change borer color based on validity of input
    if (this.activityFormValue.controls['activityName'].invalid && this.activityFormValue.controls['activityName'].touched)
    {
      document.getElementById('activityNameInput')!.className = "form-control border border-danger pl-2 round"
    }
    else
    {
      document.getElementById('activityNameInput')!.className = "form-control border border-dark pl-2 round"
    }

    // check activity description and change borer color based on validity of input
    if (this.activityFormValue.controls['activityDescription'].invalid && this.activityFormValue.controls['activityDescription'].touched)
    {
      document.getElementById('activityDescriptionInput')!.className = "form-control border border-danger pl-2 round"
    }
    else
    {
      document.getElementById('activityDescriptionInput')!.className = "form-control border border-dark pl-2 round"
    }

    if (this.activityFormValue.controls['activityCategory'].invalid && this.activityFormValue.controls['activityCategory'].touched)
    {
      document.getElementById('categorySelectList')!.className = "form-control border border-danger pl-2 round"
    }
    else
    {
      document.getElementById('categorySelectList')!.className = "form-control border border-dark pl-2 round"
    }

    if (this.activityId) // enable or disable the update button
    {
      if (this.activityFormValue.controls['activityName'].invalid || this.activityFormValue.controls['activityDescription'].invalid || this.activity.actImages.length == 0)
      {
        document.getElementById("updateButton")?.setAttribute("disabled","")
      }
      else
      {
        document.getElementById("updateButton")?.removeAttribute("disabled")
      }
    }
    else
    {
      if (this.activityFormValue.controls['activityName'].valid && this.activityFormValue.controls['activityDescription'].valid && this.activityFormValue.controls['activityCategory'].valid && this.activity.actImages.length > 0)
      {
        document.getElementById("addButton")?.removeAttribute("disabled")
      }
      else
      {
        document.getElementById("addButton")?.setAttribute("disabled","")
      }
    }
  }


  addActivityWithOneImage()
  {
    this.activity.actName = this.activityFormValue.value.activityName
    this.activity.actDescription = this.activityFormValue.value.activityDescription
    this.activity.category = this.categoryObject

    const activityFormData =  this.prepareFormData( this.activity )

    this.activityService.addActivityWithOneImage(activityFormData).subscribe({
      next:()=> {
        this.dialogRef.close()
        this.utilsService.openDialog("Opération réussite", "Activity ajoutée avec succès", true)

      },
      error: (err)=> this.utilsService.openDialog("Opération échouée", err.message, false)
    })
  }

  prepareFormData(activity: Activity): FormData
  {
    const formData = new FormData()

    formData.append(
      "activity", new Blob( [ JSON.stringify(activity) ], { type: "application/json" } )
    )
    console.log("imageFile: "  + activity.actImages.length)
    for ( let i = 0 ; i < activity.actImages.length ; i++ )
    {
      formData.append(
        "imageFile",
        activity.actImages[i].file,
        activity.actImages[i].file.name
      )
    }
    return formData
  }

  onFileSelected(event: any)
  {
    console.log(event.target.files)

    this.activity.actImages = []

    if (event.target.files)
    {
      for (let i= 0 ; i < event.target.files.length ; i++)
      {
        const file = event.target.files[i]
        const fileHandle: FileHandleModule = {
          file: file,
          url: this.sanitizer.bypassSecurityTrustUrl(
            window.URL.createObjectURL(file)
          )
        }
        this.activity.actImages.push(fileHandle)

        this.checkValidityForm()
        this.onTouched()
      }
    }
  }


  onTouched()
  {
    if (this.activity.actImages.length == 0)
    {
      if (document.getElementById("formFile"))
      {
        document.getElementById("formFile")!.className = "form-control border border-danger pl-2 round"
      }
      if (document.getElementById("formMultipleFiles"))
      {
        document.getElementById("formMultipleFiles")!.className = "form-control border border-danger pl-2 round"
      }
    }
    else
    {
      if (document.getElementById("formFile"))
      {
        document.getElementById("formFile")!.className = "form-control border border-dark pl-2 round"
      }
      if (document.getElementById("formMultipleFiles"))
      {
        document.getElementById("formMultipleFiles")!.className = "form-control border border-dark pl-2 round"
      }
    }


  }
}


